"use client";

import "../../globals.css";
import { Inter } from "next/font/google";

import Providers from "@/app/Providers";
import { Toaster } from "react-hot-toast";
import SideBar from "./SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Prosonic - Dashboard",
  description: "Generated by create next app", // <---------------------
};

export default function dashLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Toaster />
          <div className="">
            <SideBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
