const tracks = [
  {
    id: "1",
    title: "Forgetting",
    author: "Prosonic",
    daw: "Cubase",
    genre: "Hip Hop",
    length: "2:23",
    bpm: "74",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "700000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },




  {
    id: "2",
    title: "Excuses",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Hip Hop",
    length: "2:47",
    bpm: "80",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1000000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },




  {
    id: "3",
    title: "Darkness",
    author: "Prosonic",
    daw: "FLStudio",
    genre: ["Rap", "Hip hop"],
    length: "N/A",
    bpm: "145",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "500000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },




  {
    id: "4",
    title: "Hero",
    author: "Prosonic",
    daw: "FLStudio",
    genre: ["Rap", "Hip hop"],
    length: "N/A",
    bpm: "115",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "500000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },



  
  {
    id: "5",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },

























  {
    id: "6",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "7",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "8",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "9",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "10",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "11",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "12",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "13",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "14",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "15",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
  {
    id: "16",
    title: "Passion",
    author: "Prosonic",
    daw: "FLStudio",
    genre: "Pop",
    length: "N/A",
    bpm: "96",
    project_description: "N/A",
    thumbnail: "",
    tag: "PREMIUM",
    files: ["string"],
    product_type: "track",
    product_price: "1300000",
    stem_price: "500000",
    cover_price: "string",
    overall_price: "string",
  },
];

export default tracks;